apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  namespace: argocd
  labels:
    app: swiggy-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: swiggy-app
