apiVersion: v1
kind: Service
metadata:
  name: swiggy-app
  namespace: argocd
  labels:
    app: swiggy-app
spec:
  type: NodePort   # You need this if you’re using nodePort!
  selector:
    app: swiggy-app
  ports:
    - port: 81
      targetPort: 80
      nodePort: 30007
